ansible_connection: ssh
ansible_user: debian
ansible_password: Skill39
ansible_become: true
ansible_become_method: su
ansible_become_flags: '-l'
ansible_become_pass: Skill39
ansible_pty: true
domain_admin_user: Administrator
domain_realm: vme.solutions
domain_admin_pass: Skill39
